In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
iris = pd.read_csv("iris.csv")

In [4]:
copia = iris[:10]

In [6]:
copia.head(10)

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa
5           5.4          3.9           1.7          0.4  Setosa
6           4.6          3.4           1.4          0.3  Setosa
7           5.0          3.4           1.5          0.2  Setosa
8           4.4          2.9           1.4          0.2  Setosa
9           4.9          3.1           1.5          0.1  Setosa

In [7]:
max_val = copia.shape[0]

In [8]:
samples = np.random.randint(max_val, size=5)

In [10]:
copia_nan = copia.copy()

In [11]:
copia_nan.loc[samples,'petal.length'] = None

In [12]:
nan_count = copia_nan['petal.length'].isnull().sum()

In [13]:
print(str(nan_count))

4


In [14]:
copia_nan.to_csv("iris_nan_10.csv")

In [16]:
copia_nan.head(10)

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           NaN          0.2  Setosa
1           4.9          3.0           NaN          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           NaN          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa
5           5.4          3.9           1.7          0.4  Setosa
6           4.6          3.4           1.4          0.3  Setosa
7           5.0          3.4           1.5          0.2  Setosa
8           4.4          2.9           NaN          0.2  Setosa
9           4.9          3.1           1.5          0.1  Setosa

In [17]:
Y = copia_nan["variety"].values

In [18]:
X = copia_nan.drop("variety",axis=1).values

In [19]:
print(str(Y))

['Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa'
 'Setosa' 'Setosa']


In [20]:
print(str(X))

[[5.1 3.5 nan 0.2]
 [4.9 3.  nan 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 nan 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 nan 0.2]
 [4.9 3.1 1.5 0.1]]


In [21]:
copia_nan.head(10)

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           NaN          0.2  Setosa
1           4.9          3.0           NaN          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           NaN          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa
5           5.4          3.9           1.7          0.4  Setosa
6           4.6          3.4           1.4          0.3  Setosa
7           5.0          3.4           1.5          0.2  Setosa
8           4.4          2.9           NaN          0.2  Setosa
9           4.9          3.1           1.5          0.1  Setosa

In [25]:
copia_nan = copia_nan.drop("variety", axis=1)

In [26]:
copia_nan.mean()

sepal.length    4.860000
sepal.width     3.310000
petal.length    1.466667
petal.width     0.220000
dtype: float64

In [27]:
replace_with = copia_nan.mean()

In [28]:
copia_imp = copia_nan.fillna(replace_with)

In [29]:
copia_imp

sepal.length  sepal.width  petal.length  petal.width
0           5.1          3.5      1.466667          0.2
1           4.9          3.0      1.466667          0.2
2           4.7          3.2      1.300000          0.2
3           4.6          3.1      1.466667          0.2
4           5.0          3.6      1.400000          0.2
5           5.4          3.9      1.700000          0.4
6           4.6          3.4      1.400000          0.3
7           5.0          3.4      1.500000          0.2
8           4.4          2.9      1.466667          0.2
9           4.9          3.1      1.500000          0.1

In [37]:
from sklearn.impute import SimpleImputer

In [40]:
imputer = SimpleImputer(strategy="mean")

In [41]:
X_imputed = imputer.fit_transform(X)

In [42]:
print(X_imputed)

[[5.1        3.5        1.46666667 0.2       ]
 [4.9        3.         1.46666667 0.2       ]
 [4.7        3.2        1.3        0.2       ]
 [4.6        3.1        1.46666667 0.2       ]
 [5.         3.6        1.4        0.2       ]
 [5.4        3.9        1.7        0.4       ]
 [4.6        3.4        1.4        0.3       ]
 [5.         3.4        1.5        0.2       ]
 [4.4        2.9        1.46666667 0.2       ]
 [4.9        3.1        1.5        0.1       ]]
